name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install build tools
      run: sudo apt-get install mingw-w64
    - name: build
      run: x86_64-w64-mingw32-gcc -fdiagnostics-color=always -g biomehunt.c -o biomehunt.exe -Iinclude -Llibs -lminecraft_nether_gen_rs -lcubiomes -lfsg -lgcrypt -lgpg-error -lws2_32 -luserenv -lbcrypt
    - name: upload
      uses: actions/upload-artifact@v4.3.0
      with:
        path: biomehunt.exe
              
